// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AmbilJadwal():Promise<Record<string, Array<main.JadwalKelas>>>;

export function AmbilPengaturan(arg1:string):Promise<string>;

export function AmbilTugas():Promise<Array<main.Tugas>>;

export function HapusJadwal(arg1:number):Promise<void>;

export function HapusTugas(arg1:number):Promise<void>;

export function SimpanPengaturan(arg1:string,arg2:string):Promise<void>;

export function TambahJadwal(arg1:main.JadwalKelas):Promise<main.JadwalKelas>;

export function TambahTugas(arg1:main.Tugas):Promise<main.Tugas>;

export function UpdateStatusTugas(arg1:number,arg2:boolean):Promise<void>;
