// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AmbilJadwal() {
  return window['go']['main']['App']['AmbilJadwal']();
}

export function AmbilPengaturan(arg1) {
  return window['go']['main']['App']['AmbilPengaturan'](arg1);
}

export function AmbilTugas() {
  return window['go']['main']['App']['AmbilTugas']();
}

export function HapusJadwal(arg1) {
  return window['go']['main']['App']['HapusJadwal'](arg1);
}

export function HapusTugas(arg1) {
  return window['go']['main']['App']['HapusTugas'](arg1);
}

export function SimpanPengaturan(arg1, arg2) {
  return window['go']['main']['App']['SimpanPengaturan'](arg1, arg2);
}

export function TambahJadwal(arg1) {
  return window['go']['main']['App']['TambahJadwal'](arg1);
}

export function TambahTugas(arg1) {
  return window['go']['main']['App']['TambahTugas'](arg1);
}

export function UpdateStatusTugas(arg1, arg2) {
  return window['go']['main']['App']['UpdateStatusTugas'](arg1, arg2);
}
